#!/usr/bin/env ruby

rd = File.expand_path("../../../lib")
$:.unshift rd unless $:.include? rd

require 'rant'
require 'rant/plugin/configure'

task :hello do |t|
    touch t.name
end

conf = Plugin::Configure.new do |conf|
    conf.task		# define a task named :configure
    conf.check "a" do |c|
	c.default "value_a"
	c.guess { "value_a_guess" }
	c.react { |val|
	    p val
	}
    end
    conf.check "b" do |c|
	c.default "value_b"
    end
    conf.check "c" do |c|
    end
    conf.check "d" do |c|
	c.react {
	}
    end
    conf.check "e" do |c|
	c.guess { false }
    end
end

file conf["a"] do |t|
    touch t.name
end

task :clean do
    rm_f %w(config hello value_a value_a_guess)
end

if $0 == __FILE__
    Rant.run
end
